"""Initial schema with authentication and multi-tenant support

Revision ID: 24a232e81e4a
Revises: 
Create Date: 2026-02-14 11:48:41.937776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a232e81e4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_session_id'), 'projects', ['session_id'], unique=True)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_access_token'), 'user_sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_doctype', 'documents', ['project_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('extracted_text_markdown', sa.Text(), nullable=True),
    sa.Column('extracted_text_plain', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('llamaparse_time', sa.Integer(), nullable=True),
    sa.Column('pymupdf_time', sa.Integer(), nullable=True),
    sa.Column('gemini_time', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=255), nullable=True),
    sa.Column('extraction_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=True)
    op.create_table('diagram_descriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('is_diagram', sa.Boolean(), nullable=True),
    sa.Column('diagram_type', sa.String(length=100), nullable=True),
    sa.Column('outermost_elements', sa.Text(), nullable=True),
    sa.Column('shape_mapping', sa.Text(), nullable=True),
    sa.Column('nested_components', sa.Text(), nullable=True),
    sa.Column('connections', sa.Text(), nullable=True),
    sa.Column('all_text_labels', sa.Text(), nullable=True),
    sa.Column('description_summary', sa.Text(), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_descriptions_extraction_id'), 'diagram_descriptions', ['extraction_id'], unique=False)
    op.create_table('extracted_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('presigned_url', sa.String(length=1024), nullable=True),
    sa.Column('diagram_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_page', 'extracted_images', ['extraction_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_extracted_images_extraction_id'), 'extracted_images', ['extraction_id'], unique=False)
    op.create_table('extracted_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('rows_json', sa.Text(), nullable=True),
    sa.Column('num_rows', sa.Integer(), nullable=True),
    sa.Column('num_cols', sa.Integer(), nullable=True),
    sa.Column('b_box_x', sa.Integer(), nullable=True),
    sa.Column('b_box_y', sa.Integer(), nullable=True),
    sa.Column('b_box_width', sa.Integer(), nullable=True),
    sa.Column('b_box_height', sa.Integer(), nullable=True),
    sa.Column('extraction_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_table_page', 'extracted_tables', ['extraction_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_extracted_tables_extraction_id'), 'extracted_tables', ['extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_tables_extraction_id'), table_name='extracted_tables')
    op.drop_index('idx_extraction_table_page', table_name='extracted_tables')
    op.drop_table('extracted_tables')
    op.drop_index(op.f('ix_extracted_images_extraction_id'), table_name='extracted_images')
    op.drop_index('idx_extraction_page', table_name='extracted_images')
    op.drop_table('extracted_images')
    op.drop_index(op.f('ix_diagram_descriptions_extraction_id'), table_name='diagram_descriptions')
    op.drop_table('diagram_descriptions')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index('idx_project_doctype', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_access_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_session_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
